export type MusicGenreGroup = {
  id: string;
  title: string;
  description: string;
  genres: readonly string[];
};

export const musicGenreGroups: readonly MusicGenreGroup[] = [
  {
    id: 'africa-now',
    title: 'Africa Now',
    description: 'The sounds moving clubs, charts, streets and festivals across the continent right now.',
    genres: [
      'Amapiano',
      'Afrobeats',
      'Afro-pop',
      'Afrofusion',
      'Afro-house',
      'Afrotech',
      'Gqom',
      'Kwaito',
      'Alté',
      'Bongo Flava',
      'Gengetone',
      'Highlife',
      'Hiplife',
      'Soukous',
      'Ndombolo',
      'Afro-soul',
      'Afro-jazz',
    ],
  },
  {
    id: 'southern-roots',
    title: 'Southern African Roots',
    description: 'Heritage and regional sounds from Southern Africa, from vocal traditions to dance-floor classics.',
    genres: [
      'Traditional / Indigenous',
      'Maskandi',
      'Mbaqanga',
      'Marabi',
      'Isicathamiya',
      'Mbube',
      'Cape Jazz',
      'Ghoema',
      'Riel Music',
      'Langarm',
      'Chimurenga',
      'Sungura',
      'Marrabenta',
      'Choral',
    ],
  },
  {
    id: 'continental-roots',
    title: 'Continental Roots',
    description: 'Distinctive music traditions and regional genres from across Africa and its islands.',
    genres: [
      'Mbalax',
      'Juju',
      'Fuji',
      'Palm-wine',
      'Congolese Rumba',
      'Makossa',
      'Bikutsi',
      'Taarab',
      'Ethio-jazz',
      'Kizomba',
      'Semba',
      'Kuduro',
      'Morna',
      'Funaná',
      'Sega',
      'Maloya',
      'Raï',
      'Chaabi',
      'Gnawa',
      'Folk',
      'World Music',
      'Bhangra',
    ],
  },
  {
    id: 'faith-inspiration',
    title: 'Faith & Inspiration',
    description: 'Music for worship, reflection, celebration, testimony and community.',
    genres: [
      'Gospel',
      'Contemporary Gospel',
      'Praise & Worship',
      'Choir',
      'Christian Contemporary',
      'Sacred / Spiritual',
      'Traditional Spirituals',
      'Nasheed',
    ],
  },
  {
    id: 'global',
    title: 'Global Sounds',
    description: 'International genres with African artists, audiences and cross-cultural collaborations welcome.',
    genres: [
      'Hip-Hop / Rap',
      'R&B',
      'Soul',
      'Pop',
      'Jazz',
      'Blues',
      'Reggae',
      'Dancehall',
      'House',
      'Electronic / EDM',
      'Rock',
      'Alternative',
      'Indie',
      'Funk',
      'Disco',
      'Classical',
      'Orchestral',
      'Opera',
      'Country',
      'Latin',
    ],
  },
] as const;

export const musicPerformanceFormats = [
  'Live concert',
  'Festival',
  'DJ set',
  'Acoustic / unplugged',
  'Choir concert',
  'Worship service',
  'Cypher / battle',
  'Studio session',
  'Music documentary',
  'Album listening premiere',
] as const;

export const allMusicGenres = Array.from(
  new Set(musicGenreGroups.flatMap((group) => [...group.genres])),
);
