export const PORTFOLIO = [
  {
    id: 'allegro',
    name: 'ALLEGRO',
    category: 'Music & entertainment',
    audience: 'listeners, artists and creators',
    promise: 'Discover music, grow artists and connect audiences to live entertainment.',
    cta: 'LISTEN NOW',
    accent: '#38f0ff',
    background: '#210033',
    font: 'Bebas Neue',
    visualCue: 'Artists • live performance • audio player • concert energy',
  },
  {
    id: 'kora',
    name: 'KORA',
    category: 'African entertainment network',
    audience: 'fans, artists and entertainment audiences',
    promise: 'African music, entertainment, artists and live experiences built for the world.',
    cta: 'EXPLORE KORA',
    accent: '#ffb100',
    background: '#120b04',
    font: 'Archivo Black',
    visualCue: 'African performance • artists • Kora instrument • live-event energy',
  },
  {
    id: 'edubuild',
    name: 'EDU-BUILD ECD360',
    category: 'ECD training & learning',
    audience: 'ECD students and practitioners',
    promise: 'Train, learn and progress through ECD study pathways with digital and campus support.',
    cta: 'START LEARNING',
    accent: '#27d6c5',
    background: '#063d48',
    font: 'Poppins',
    visualCue: 'ECD classroom • facilitator • learner journey • virtual teaching',
  },
  {
    id: 'faisready',
    name: 'FAISREADY',
    category: 'Regulatory exam preparation',
    audience: 'financial-services professionals preparing for regulatory exams',
    promise: 'Prepare for regulatory exams with focused learning, practice and exam-readiness support.',
    cta: 'START PREPARING',
    accent: '#62e45f',
    background: '#071a13',
    font: 'Oswald',
    visualCue: 'Exam prep • practice questions • progress dashboard • professional learning',
  },
  {
    id: 'mandatory-reg-exams',
    name: 'MANDATORY REGULATORY EXAMS',
    category: 'Multi-industry regulatory exam preparation',
    audience: 'professionals who must pass mandatory industry exams',
    promise: 'Find your regulatory exam and prepare through one recognisable exam-focused platform.',
    cta: 'FIND YOUR EXAM',
    accent: '#6ee7ff',
    background: '#06111f',
    font: 'Archivo Black',
    visualCue: 'Exam badges • industry icons • learning dashboard • assessment readiness',
  },
  {
    id: 'auto-ai',
    name: 'AUTO AI',
    category: 'Vehicle repair second opinion',
    audience: 'drivers facing repair quotes or vehicle problems',
    promise: 'Get a clearer second opinion on a repair quote before you approve the work.',
    cta: 'CHECK MY QUOTE',
    accent: '#ff6b00',
    background: '#0d0d0d',
    font: 'Bebas Neue',
    visualCue: 'Vehicle • diagnostic scan • repair quote • workshop technology',
  },
  {
    id: 'learners',
    name: 'SA LEARNER DRIVER LICENCE',
    category: 'Learner-driver preparation',
    audience: 'South Africans preparing for learner-driver licence tests',
    promise: 'Prepare for Codes 08, 10, 14 and motorcycles with signs, practice and simulation.',
    cta: 'START PRACTISING',
    accent: '#ffd43b',
    background: '#10213a',
    font: 'Oswald',
    visualCue: 'Road signs • learner car • motorcycle • simulator • test practice',
  },
  {
    id: 'pimp-car',
    name: 'PIMP MY OLD CAR',
    category: 'Vehicle visualisation & customisation',
    audience: 'owners who want to transform older vehicles',
    promise: 'Upload your car, visualise a dramatic new look and move toward a real-world transformation.',
    cta: 'UPLOAD MY CAR',
    accent: '#ff2bd6',
    background: '#110914',
    font: 'Archivo Black',
    visualCue: 'Before/after custom cars • glossy paint • wheels • dramatic transformation',
  },
  {
    id: 'doxa-sure',
    name: 'DOXA-SURE',
    category: 'Protection & support platform',
    audience: 'people and households seeking practical protection and support services',
    promise: 'Connect people to clear protection, assistance and resilience support through one platform.',
    cta: 'SEE YOUR OPTIONS',
    accent: '#7ad7ff',
    background: '#091424',
    font: 'Poppins',
    visualCue: 'Protection • support • trusted assistance • clear service dashboard',
  },
  {
    id: 'chancellor',
    name: 'THE CHANCELLOR',
    category: 'Business growth desk',
    audience: 'small and growing businesses',
    promise: 'Identify what is holding your business back and move toward practical growth actions.',
    cta: 'START BUSINESS CHECK',
    accent: '#d6b55b',
    background: '#0e1015',
    font: 'Playfair Display',
    visualCue: 'Business owner • growth dashboard • roadmap • advisory interaction',
  },
  {
    id: 'nextradefinx',
    name: 'NEXTRADEFINX',
    category: 'Market education & paper trading',
    audience: 'people learning financial markets',
    promise: 'Learn markets, explore intelligence and practise with paper trading before risking real money.',
    cta: 'START LEARNING',
    accent: '#42e8b4',
    background: '#071411',
    font: 'Archivo Black',
    visualCue: 'Market charts • education • intelligence dashboard • paper trading',
  },
  {
    id: 'izakhono-websites',
    name: 'IZAKHONO BUSINESS WEBSITES',
    category: 'Affordable business websites',
    audience: 'small businesses that need a professional online presence',
    promise: 'Get a clear, professional business website designed to help customers understand and contact you.',
    cta: 'GET MY WEBSITE',
    accent: '#b8ff3d',
    background: '#08100a',
    font: 'Archivo Black',
    visualCue: 'Website mockups • phone and laptop • business owner • enquiry flow',
  },
  {
    id: 'izakhono-gamer',
    name: 'IZAKHONO GAMER STUDIO',
    category: 'Gaming creator & esports suite',
    audience: 'gamers, streamers, esports teams and game creators',
    promise: 'Create stream graphics, gaming thumbnails, esports media and creator assets with the full Creative Suite included.',
    cta: 'JOIN FOR $15',
    accent: '#42f5c5',
    background: '#070913',
    font: 'Archivo Black',
    visualCue: 'Gameplay energy • stream overlay • esports player • creator setup • game-dev assets',
  },
];

export const CAMPAIGN_LEVELS = [
  { id: 'awareness', name: 'Awareness', lead: 'MAKE THEM NOTICE', purpose: 'Introduce the platform and its promise.' },
  { id: 'benefit', name: 'Benefit', lead: 'SHOW THE VALUE', purpose: 'Lead with the strongest practical benefit.' },
  { id: 'offer', name: 'Offer', lead: 'GIVE THEM A REASON NOW', purpose: 'Feature the current price, package or offer when supplied.' },
  { id: 'conversion', name: 'Conversion', lead: 'TELL THEM WHAT TO DO', purpose: 'Use a direct CTA and remove distraction.' },
  { id: 'retarget', name: 'Retargeting', lead: 'BRING THEM BACK', purpose: 'Remind previous visitors what they can gain.' },
  { id: 'share', name: 'Shareable', lead: 'MAKE IT WORTH SHARING', purpose: 'Create simple high-clarity social creative for organic sharing.' },
];

export const CAMPAIGN_FORMATS = [
  'Instagram Post',
  'Story / Reel',
  'Facebook Post',
  'LinkedIn Post',
  'YouTube Thumbnail',
];
