export const SUITE_PRICE = {
  currency: 'USD',
  monthly: 5,
  label: '$5/month',
  billing: 'monthly',
  coreAccess: 'all-core-tools',
  aiPolicy: 'starter-allowance-plus-optional-topups',
};

export const SUITE_TOOLS = [
  {
    id: 'design',
    name: 'Canvas',
    kicker: 'Design + social',
    status: 'working-v1',
    description: 'Posters, social creatives, thumbnails, campaigns, templates, brand kits and fast browser export.',
    replaces: 'Separate design and express-style workflows',
  },
  {
    id: 'photo',
    name: 'Photo Lab',
    kicker: 'Photo editing',
    status: 'working-v1',
    description: 'Local browser photo adjustments, rotation, flips and PNG export without uploading the source file.',
    replaces: 'Everyday raster editing workflows',
  },
  {
    id: 'campaign',
    name: 'Campaign Engine',
    kicker: 'Marketing automation',
    status: 'working-v1',
    description: 'One brief generates portfolio-scale creative packs, placements and social copy across major formats.',
    replaces: 'Manual creative resizing and campaign packaging',
  },
  {
    id: 'vector',
    name: 'Vector',
    kicker: 'Logos + illustration',
    status: 'foundation',
    description: 'SVG-first illustration, shapes, pen paths, boolean operations, gradients, typography and reusable symbols.',
    replaces: 'Vector illustration workflows',
  },
  {
    id: 'layout',
    name: 'Layout',
    kicker: 'Publishing',
    status: 'foundation',
    description: 'Multi-page documents, brochures, magazines, books, print layouts, master pages and press-ready export.',
    replaces: 'Desktop publishing workflows',
  },
  {
    id: 'video',
    name: 'Cut',
    kicker: 'Video editing',
    status: 'foundation',
    description: 'Timeline video editor with captions, transitions, proxy media, templates, multicam-ready architecture and exports.',
    replaces: 'General video editing workflows',
  },
  {
    id: 'motion',
    name: 'Motion',
    kicker: 'Animation + VFX',
    status: 'foundation',
    description: 'Motion graphics, keyframes, compositing, titles, masks, chroma key and reusable animated brand systems.',
    replaces: 'Motion graphics and compositing workflows',
  },
  {
    id: 'audio',
    name: 'Wave',
    kicker: 'Audio',
    status: 'foundation',
    description: 'Waveform editing, multitrack sessions, noise cleanup, podcast tools, voice processing and loudness export.',
    replaces: 'Audio cleanup and multitrack workflows',
  },
  {
    id: 'pdf',
    name: 'DocFlow',
    kicker: 'PDF + documents',
    status: 'foundation',
    description: 'Create, combine, annotate, sign, compress, convert and organise PDF/document workflows in one place.',
    replaces: 'PDF utility and document workflows',
  },
  {
    id: 'ai',
    name: 'AI Lab',
    kicker: 'Generative tools',
    status: 'foundation',
    description: 'Provider-portable image, copy, background, translation, caption and creative-assistant tools with cost controls.',
    replaces: 'Separate generative add-ons',
  },
  {
    id: 'assets',
    name: 'Assets',
    kicker: 'Fonts + media',
    status: 'foundation',
    description: 'Brand kits, fonts, logos, photos, video, audio, templates and reusable components shared by every tool.',
    replaces: 'Disconnected asset libraries',
  },
  {
    id: 'publish',
    name: 'Publish',
    kicker: 'Share + distribute',
    status: 'foundation',
    description: 'Export once, resize, package and route approved content to owned channels and authorised external accounts.',
    replaces: 'Separate handoff and publishing steps',
  },
];

export const SUITE_PROMISES = [
  'One subscription instead of separate app paywalls',
  'One project format shared across every creative tool',
  'Browser-first and lightweight, with local processing where practical',
  'IZAKHONO-owned infrastructure as the primary destination',
  'External infrastructure remains reversible for availability and resilience',
  'Portfolio campaign automation built into the creative suite',
  'AI providers remain interchangeable instead of locking the product to one vendor',
  'Global-first templates with African design and language support built in',
];
