const qs=s=>document.querySelector(s);const qsa=s=>Array.from(document.querySelectorAll(s));
const CODES={P0300:["Random/multiple cylinder misfire detected","ignition, fuel delivery, vacuum leak, compression or timing"],P0301:["Cylinder 1 misfire detected","spark plug, ignition coil, injector, compression or wiring"],P0302:["Cylinder 2 misfire detected","spark plug, ignition coil, injector, compression or wiring"],P0303:["Cylinder 3 misfire detected","spark plug, ignition coil, injector, compression or wiring"],P0304:["Cylinder 4 misfire detected","spark plug, ignition coil, injector, compression or wiring"],P0420:["Catalyst system efficiency below threshold (Bank 1)","exhaust leak, oxygen sensor, misfire history or catalytic converter"],P0430:["Catalyst system efficiency below threshold (Bank 2)","exhaust leak, oxygen sensor, misfire history or catalytic converter"],P0171:["System too lean (Bank 1)","vacuum leak, MAF issue, low fuel pressure, injector or exhaust leak"],P0172:["System too rich (Bank 1)","injector leak, fuel pressure, MAF/MAP issue, oxygen sensor or restricted air intake"],P0299:["Turbo/supercharger underboost","boost leak, actuator/wastegate, turbo wear, sensor or exhaust restriction"],P0128:["Coolant temperature below thermostat regulating temperature","thermostat, coolant temperature sensor or cooling-system issue"],P0401:["EGR flow insufficient","blocked EGR passages, valve, sensor or vacuum/control fault"],P0455:["EVAP system large leak","fuel cap, hose, purge/vent valve or damaged EVAP component"]};
const stops=[["brake pedal","soft brake pedal"],["no brakes","braking system"],["oil pressure","oil pressure warning"],["overheat","overheating"],["temperature red","high coolant temperature"],["steering locked","steering fault"],["fuel leak","fuel leak"],["petrol leak","fuel leak"],["diesel leak","fuel leak"],["smoke from engine","engine-bay smoke"],["fire","possible fire"],["wheel loose","wheel/security issue"]];
const cautions=[["flashing engine","flashing check-engine light"],["misfire","engine misfire"],["loss of power","power loss"],["limp mode","limp mode"],["abs light","ABS warning"],["airbag light","airbag/SRS warning"],["battery light","charging-system warning"],["vibration","abnormal vibration"]];
const text=x=>String(x||"").trim();const found=(t,a)=>a.find(x=>t.toLowerCase().includes(x[0]));
function localTriage(input){const s=text(input.symptoms)+" "+text(input.warningLights);const stop=found(s,stops),caution=found(s,cautions),urgency=stop?"STOP":caution?"URGENT":"CHECK";return{urgency,safety:stop?"Stop driving as soon as it is safe to do so and arrange qualified inspection or recovery. Do not rely on this app alone.":caution?"Limit driving until the fault is properly checked. If the warning becomes red, severe, or handling/braking changes, stop safely.":"No immediate stop condition was identified from the information supplied, but symptoms still require proper inspection if they persist.",likely_categories:stop?[stop[1]]:caution?[caution[1]]:["maintenance or mechanical/electrical fault requiring structured checks"],next_checks:["Confirm exact warning lights/messages and whether they are steady or flashing.","Record when the symptom occurs: cold/hot, idle/acceleration, speed, load and weather.","Check fluid levels only when safe and according to the vehicle handbook.","Retrieve diagnostic trouble codes if available before replacing parts."],confidence:"preliminary",disclaimer:"This is decision support, not a confirmed mechanical diagnosis.",source:"browser-safety-engine"}}
function localCode(input){const code=text(input.code).toUpperCase().replace(/[^A-Z0-9]/g,""),hit=CODES[code];return hit?{code,meaning:hit[0],possibleCauses:hit[1],advice:"Treat the code as evidence, not a parts order. Check freeze-frame/live data and test the system before replacing expensive components.",disclaimer:"Manufacturer-specific meanings can differ. Confirm against the correct service information for the exact vehicle."}:{code,meaning:"Code not in the starter library.",possibleCauses:"Manufacturer-specific information or a deeper diagnostic service is needed.",advice:"Do not replace a component based only on an unfamiliar code."}}
function localQuote(input){const q=text(input.quote),flags=[];if(q.length<40)flags.push("The quotation is too brief to verify what work is actually included.");if(!/(labou?r|hours|hrs)/i.test(q))flags.push("Labour hours/rate are not clearly shown.");if(!/(part|plug|coil|sensor|pump|filter|belt|disc|pad|battery|tyre|injector|turbo|radiator|service)/i.test(q))flags.push("Parts or repair items are not clearly itemised.");if(!/(diagnos|test|scan|inspection|pressure|compression|voltage)/i.test(q))flags.push("The quote does not clearly show the test/diagnosis that justified the repair.");if(/ecu|gearbox|engine|turbo|catalytic|module|injector/i.test(q))flags.push("This includes a high-value component. Ask for the test evidence before authorising replacement.");return{result:flags.length?"REVIEW BEFORE APPROVING":"REASONABLY ITEMISED",flags,askWorkshop:["What test confirmed each major part needs replacement?","Are parts new, OEM, aftermarket, rebuilt or used?","What labour hours and hourly rate are included?","What warranty applies to parts and labour?","Will I be contacted before any additional work is done?"],disclaimer:"AUTO AI checks clarity and decision quality; it does not certify a workshop quotation as correct."}}
function localBuyer(input){let score=100,concerns=[];(input.issues||[]).forEach(i=>{if(!i.checked)return;score-=i.severity==="high"?18:i.severity==="low"?5:10;concerns.push(i.label)});score=Math.max(0,Math.min(100,score));return{score,band:score>=85?"LOWER RISK":score>=70?"PROCEED WITH CHECKS":score>=50?"HIGH CAUTION":"WALK AWAY / EXPERT INSPECTION",concerns,next:["Verify VIN and ownership/documentation independently.","Request service and repair history.","Do a cold start and full road test.","Use an independent physical inspection before purchase when material concerns exist."],disclaimer:"This score is a screening aid, not a roadworthy certificate, valuation, title check or mechanical guarantee."}}
async function post(endpoint,data){try{const r=await fetch("api/"+endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error("API unavailable");return await r.json()}catch{if(endpoint==="triage")return localTriage(data);if(endpoint==="fault-code")return localCode(data);if(endpoint==="quote-review")return localQuote(data);if(endpoint==="used-car-score")return localBuyer(data);throw new Error("AUTO AI could not complete that request.")}}
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function list(items){items=items||[];return items.length?"<ul>"+items.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul>":""}
function loading(form,on){const b=form.querySelector("button[type=submit]");if(!b)return;b.disabled=on;b.dataset.old=b.dataset.old||b.textContent;b.textContent=on?"Analysing...":b.dataset.old}
function show(el,html){el.innerHTML=html;el.hidden=false;el.scrollIntoView({behavior:"smooth",block:"nearest"})}
qsa(".action").forEach(btn=>btn.addEventListener("click",()=>{qsa(".action").forEach(x=>x.classList.remove("active"));qsa(".panel").forEach(x=>x.classList.remove("active"));btn.classList.add("active");qs("#"+btn.dataset.panel).classList.add("active")}));
(async()=>{const s=qs("#statusBar");try{const r=await fetch("api/health",{cache:"no-store"});if(!r.ok)throw 0;const h=await r.json();s.classList.add("ok");s.innerHTML='<span class="dot"></span><span>AUTO AI ready · '+(h.aiConfigured?"connected AI service":"server safety engine active")+"</span>"}catch{s.classList.add("ok");s.innerHTML='<span class="dot"></span><span>AUTO AI ready · browser safety engine active</span>'}})();
qs("#triageForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget;loading(f,true);try{const r=await post("triage",Object.fromEntries(new FormData(f))),cls=r.urgency==="STOP"||r.urgency==="URGENT"?"urgent":"good";show(qs("#triageResult"),'<h3 class="'+cls+'">'+esc(r.urgency)+' — preliminary assessment</h3><p><strong>Safety:</strong> '+esc(r.safety)+'</p><p><strong>Likely area(s):</strong></p>'+list(r.likely_categories)+'<p><strong>Next checks:</strong></p>'+list(r.next_checks)+'<p><small>'+esc(r.disclaimer||"")+"</small></p>")}catch(err){show(qs("#triageResult"),'<h3 class="urgent">Could not analyse</h3><p>'+esc(err.message)+"</p>")}loading(f,false)});
qs("#codeForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget;loading(f,true);try{const r=await post("fault-code",Object.fromEntries(new FormData(f)));show(qs("#codeResult"),"<h3>"+esc(r.code)+" — "+esc(r.meaning)+"</h3><p><strong>Possible areas:</strong> "+esc(r.possibleCauses)+"</p><p>"+esc(r.advice)+"</p><p><small>"+esc(r.disclaimer||"")+"</small></p>")}catch(err){show(qs("#codeResult"),'<h3 class="urgent">Could not explain code</h3><p>'+esc(err.message)+"</p>")}loading(f,false)});
qs("#quoteForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget;loading(f,true);try{const r=await post("quote-review",Object.fromEntries(new FormData(f)));show(qs("#quoteResult"),"<h3>"+esc(r.result)+"</h3>"+(r.flags.length?'<p><strong>Things to clarify:</strong></p>'+list(r.flags):'<p class="good">The pasted quote contains useful itemisation, but still confirm the diagnosis.</p>')+'<p><strong>Ask the workshop:</strong></p>'+list(r.askWorkshop)+"<p><small>"+esc(r.disclaimer)+"</small></p>")}catch(err){show(qs("#quoteResult"),'<h3 class="urgent">Could not review quote</h3><p>'+esc(err.message)+"</p>")}loading(f,false)});
qs("#buyerForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget;loading(f,true),issues=qsa("#buyerForm input[type=checkbox]").map(x=>({label:x.dataset.label,severity:x.dataset.severity,checked:x.checked}));try{const r=await post("used-car-score",{issues});show(qs("#buyerResult"),'<div class="score">'+r.score+'/100</div><h3>'+esc(r.band)+"</h3>"+(r.concerns.length?'<p><strong>Reported concerns:</strong></p>'+list(r.concerns):'<p class="good">No concerns were selected in this first screen.</p>')+'<p><strong>Before buying:</strong></p>'+list(r.next)+"<p><small>"+esc(r.disclaimer)+"</small></p>")}catch(err){show(qs("#buyerResult"),'<h3 class="urgent">Could not score vehicle</h3><p>'+esc(err.message)+"</p>")}loading(f,false)});
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;qs("#installBtn").hidden=false});qs("#installBtn").addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;qs("#installBtn").hidden=true});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
