'use client';
import { useMemo,useState,useTransition } from 'react'; import type { SiteTemplate } from '@/lib/site-templates'; import { createProjectAction } from './actions';
type Service={name:string;description:string};
export default function ProjectBuilderForm({templates}:{templates:SiteTemplate[]}){
 const [pending,startTransition]=useTransition(); const [message,setMessage]=useState(''); const [templateKey,setTemplateKey]=useState(templates[0]?.key??'');
 const [services,setServices]=useState<Service[]>([{name:'Our Service',description:'Describe what you provide and who it helps.'}]);
 const [form,setForm]=useState({name:'',slug:'',businessName:'',tagline:'',about:'',email:'',phone:'',whatsapp:'',address:'',primaryColor:'#0f172a',secondaryColor:'#16a34a',facebook:'',instagram:'',linkedin:''});
 const selected=useMemo(()=>templates.find(t=>t.key===templateKey),[templates,templateKey]); const update=(f:string,v:string)=>setForm(c=>({...c,[f]:v}));
 const submit=()=>{setMessage('');startTransition(async()=>{const r=await createProjectAction({name:form.name||form.businessName,slug:form.slug,templateKey,content:{businessName:form.businessName,tagline:form.tagline,about:form.about,email:form.email,phone:form.phone,whatsapp:form.whatsapp,address:form.address,primaryColor:form.primaryColor,secondaryColor:form.secondaryColor,facebook:form.facebook,instagram:form.instagram,linkedin:form.linkedin,services}}); if(r?.ok===false)setMessage(r.message);});};
 return <div className='mt-10 grid gap-8 lg:grid-cols-[1.15fr_.85fr]'><section className='space-y-8'>
 <div><h2 className='text-xl font-semibold'>1. Choose a template</h2><div className='mt-4 grid gap-3 sm:grid-cols-2'>{templates.map(t=><button type='button' key={t.key} onClick={()=>setTemplateKey(t.key)} className={`rounded-2xl border p-4 text-left ${templateKey===t.key?'border-slate-950 bg-slate-50':''}`}><p className='font-semibold'>{t.name}</p><p className='mt-1 text-sm text-slate-600'>{t.description}</p></button>)}</div></div>
 <div><h2 className='text-xl font-semibold'>2. Business details</h2><div className='mt-4 grid gap-4'>{[['Website project name','name'],['Website address name','slug'],['Business or organisation name','businessName'],['Tagline','tagline'],['Email','email'],['Phone','phone'],['WhatsApp','whatsapp'],['Address','address']].map(([l,f])=><label key={f} className='grid gap-2'><span className='text-sm font-medium'>{l}</span><input className='rounded-xl border px-4 py-3' value={(form as any)[f]} onChange={e=>update(f,e.target.value)}/></label>)}<label className='grid gap-2'><span className='text-sm font-medium'>About your organisation</span><textarea className='min-h-36 rounded-xl border px-4 py-3' value={form.about} onChange={e=>update('about',e.target.value)}/></label></div></div>
 <div><h2 className='text-xl font-semibold'>3. Branding</h2><div className='mt-4 grid grid-cols-2 gap-4'><label className='grid gap-2'><span className='text-sm font-medium'>Primary colour</span><input type='color' className='h-12 w-full rounded-xl border p-1' value={form.primaryColor} onChange={e=>update('primaryColor',e.target.value)}/></label><label className='grid gap-2'><span className='text-sm font-medium'>Accent colour</span><input type='color' className='h-12 w-full rounded-xl border p-1' value={form.secondaryColor} onChange={e=>update('secondaryColor',e.target.value)}/></label></div></div>
 <div><h2 className='text-xl font-semibold'>4. Services or products</h2><div className='mt-4 space-y-4'>{services.map((s,i)=><div key={i} className='rounded-2xl border p-4'><input className='w-full rounded-xl border px-4 py-3' value={s.name} onChange={e=>{const n=[...services];n[i]={...n[i],name:e.target.value};setServices(n)}}/><textarea className='mt-3 min-h-24 w-full rounded-xl border px-4 py-3' value={s.description} onChange={e=>{const n=[...services];n[i]={...n[i],description:e.target.value};setServices(n)}}/></div>)}<button type='button' className='rounded-xl border px-4 py-2 font-medium' onClick={()=>services.length<12&&setServices([...services,{name:'',description:''}])}>Add another</button></div></div>
 {message&&<p className='rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700'>{message}</p>}<button type='button' disabled={pending} onClick={submit} className='rounded-xl bg-slate-950 px-6 py-3 font-semibold text-white disabled:opacity-50'>{pending?'Creating...':'Save website draft'}</button>
 </section><aside className='lg:sticky lg:top-8 lg:self-start'><div className='overflow-hidden rounded-3xl border bg-white shadow-sm'><div className='p-8 text-white' style={{backgroundColor:form.primaryColor}}><p className='text-sm opacity-80'>{selected?.name}</p><h2 className='mt-3 text-3xl font-bold'>{form.businessName||'Your business name'}</h2><p className='mt-3 opacity-90'>{form.tagline||'Your tagline will appear here.'}</p><span className='mt-6 inline-block rounded-xl px-4 py-2 font-semibold' style={{backgroundColor:form.secondaryColor}}>Contact us</span></div><div className='p-8'><h3 className='text-xl font-semibold'>About</h3><p className='mt-3 whitespace-pre-wrap text-sm text-slate-600'>{form.about||'Tell customers what makes your organisation valuable.'}</p></div></div></aside></div>
}
