create extension if not exists pgcrypto;
create table if not exists public.learner_passports (user_id uuid primary key references auth.users(id) on delete cascade,language_code text not null default 'en',experience_level text not null default 'beginner',learning_goal text not null default 'understand_markets',current_stage integer not null default 0 check (current_stage between 0 and 5),beta_age_confirmed_18_plus boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.learner_passports enable row level security;
create policy "passport_select_own" on public.learner_passports for select using (auth.uid()=user_id);
create policy "passport_insert_own" on public.learner_passports for insert with check (auth.uid()=user_id);
create policy "passport_update_own" on public.learner_passports for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create table if not exists public.learning_events (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,event_type text not null,event_payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());
alter table public.learning_events enable row level security;
create policy "learning_events_select_own" on public.learning_events for select using (auth.uid()=user_id);
create policy "learning_events_insert_own" on public.learning_events for insert with check (auth.uid()=user_id);
