import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {configureTicketSettlement,createTicketEvent,publishTicketPreview,setTicketSales} from './actions';

export default async function TicketOps({searchParams}:{searchParams:Promise<{error?:string}>}){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect('/login');
 const{data:p}=await s.from('profiles').select('role').eq('id',user.id).maybeSingle();if(!p||!['moderator','admin'].includes(p.role))redirect('/');
 const{error}=await searchParams;
 const[eventsResult,creatorsResult]=await Promise.all([
  s.from('ticket_events').select('id,title,starts_at,event_mode,status,sales_enabled,creator_id,artist_share_bps,settlement_hold_hours').order('starts_at'),
  s.from('creators').select('id,name,verified').order('name'),
 ]);
 const creators=creatorsResult.data??[];const creatorNames=new Map(creators.map(c=>[c.id,c.name]));
 return <main>
  <section className="subHero"><div className="eyebrow">KORA TICKET OPERATIONS</div><h1>KORA collects. Artists get a transparent settlement.</h1><p>The fan pays KORA. Every cleared ticket creates a recorded split between the artist/promoter and KORA, held until after the event before it can enter the beneficiary wallet.</p></section>
  <section className="dashMain">
   {error?<div className="panel"><strong>{error}</strong></div>:null}
   {eventsResult.error?<div className="panel"><strong>Schema 19 must be activated before ticket settlement operations can open.</strong></div>:null}
   <form action={createTicketEvent} className="panel formPanel"><h3>Create event and first ticket tier</h3><div className="formGrid"><label>Title<input name="title" required/></label><label>URL slug<input name="slug" required/></label><label>Start<input name="starts_at" type="datetime-local" required/></label><label>Mode<select name="event_mode"><option value="venue">Venue</option><option value="online">Online</option><option value="hybrid">Hybrid</option></select></label><label>Venue<input name="venue_name"/></label><label>City<input name="venue_city"/></label><label>Tier name<input name="tier_name" defaultValue="General"/></label><label>Price (ZAR)<input name="price" type="number" min="0" step=".01" required/></label><label>Capacity<input name="capacity" type="number" min="1" required/></label><label>Artist / promoter beneficiary<select name="creator_id" defaultValue=""><option value="">KORA-operated event (100% KORA)</option>{creators.map(c=><option value={c.id} key={c.id}>{c.name}{c.verified?' • verified':''}</option>)}</select></label><label>Beneficiary share %<input name="artist_share_percent" type="number" min="0" max="90" step=".1" defaultValue="90"/></label><label>Settlement hold after event (hours)<input name="settlement_hold_hours" type="number" min="0" max="720" step="1" defaultValue="48"/></label></div><label>Description<textarea name="description" minLength={40} rows={5} required/></label><p><small>If no beneficiary is selected, KORA automatically records a 0% beneficiary share. For artist/promoter events the default commercial split is 90% beneficiary / 10% KORA.</small></p><button className="primary">Create draft</button></form>
   <div className="panel"><h3>Events & settlement agreements</h3>{(eventsResult.data??[]).map(e=><article className="moderationItem" key={e.id}><div><strong>{e.title}</strong><p>{e.status} • {e.event_mode} • {new Date(e.starts_at).toLocaleString('en-ZA')} • beneficiary {e.creator_id?creatorNames.get(e.creator_id)||'Configured account':'KORA'} • share {(e.artist_share_bps/100).toFixed(1)}% • hold {e.settlement_hold_hours??48}h • sales {e.sales_enabled?'ON':'LOCKED'}</p></div><form action={configureTicketSettlement} className="formPanel"><input type="hidden" name="event_id" value={e.id}/><div className="formGrid"><label>Artist / promoter<select name="creator_id" defaultValue={e.creator_id??''} disabled={e.sales_enabled}><option value="">KORA-operated event</option>{creators.map(c=><option value={c.id} key={c.id}>{c.name}{c.verified?' • verified':''}</option>)}</select></label><label>Beneficiary share %<input name="artist_share_percent" type="number" min="0" max="90" step=".1" defaultValue={e.artist_share_bps/100} disabled={e.sales_enabled}/></label><label>Hold hours<input name="settlement_hold_hours" type="number" min="0" max="720" step="1" defaultValue={e.settlement_hold_hours??48} disabled={e.sales_enabled}/></label></div><button className="secondary" disabled={e.sales_enabled}>Save settlement agreement</button>{e.sales_enabled?<small>Lock sales before changing the settlement agreement.</small>:null}</form><div className="actions"><form action={publishTicketPreview}><input type="hidden" name="event_id" value={e.id}/><button className="secondary">Publish safe preview</button></form><form action={setTicketSales}><input type="hidden" name="event_id" value={e.id}/><button className="primary" name="enabled" value={e.sales_enabled?'false':'true'}>{e.sales_enabled?'Lock sales':'Enable configured checkout'}</button></form></div></article>)}<p><a className="secondary" href="/admin/tickets/check-in">Open venue check-in →</a> <a className="secondary" href="/admin/payouts">Open settlements & payouts →</a></p></div>
  </section>
 </main>
}
